### ISSUE TITLE
Push polling quits after an update for the containing layout

### ISSUE THREAD

**Issue by jouni** [R2R/ICEPush-for-Vaadin#1]
Culprit: https://github.com/R2R/ICEPush-for-Vaadin/blob/master/src/org/vaadin/artur/icepush/client/ui/VICEPush.java#L133

The onDetach method is called at least during the update for a VCssLayout, which removes all contained children every time it is updated and then adds them back.

**Comment by Artur-** [comment]
Fixed when converting from a widget to an extension
